### ISSUE TITLE
consider making libimaevm thread-safe

### ISSUE THREAD

**Issue by fche** [linux-integrity/ima-evm-utils#3]
libimaevm has a couple of global variables that are not concurrency-safe.  Please consider documenting this formally, or adding pthread locking around e.g. the static var public_keys;

**Comment by mimizohar** [comment]
Another option would be to update the library function definitions to include public_keys and select imaevm_param variables as parameters.

**Comment by mimizohar** [comment]
The changes for making libimaevm thread safe are now available in the v1.6 release.

**Comment by mimizohar** [comment]
The changes for making libimaevm thread safe are now available in the v1.6 release.

**Comment by nikableh** [comment]
> The changes for making libimaevm thread safe are now available in the v1.6 release.

What was changed exactly? I still see `imaevm_param` as a global mutable variable in v1.6 release.
