### ISSUE TITLE
consider licensing libimaevm with GPL2+ rather than GPL2-only

### ISSUE THREAD

**Issue by fche** [linux-integrity/ima-evm-utils#4]
While the developers may not have envisioned libimaevm being useful to build anything other than the tools right here, there are other possible uses.  Over in elfutils debuginfod, we have prototyped using this library to check rpm/ima signatures in userspace.  However, its license (GPL2-only) makes it incompatible with other indirect users of elfutils (some GPL3-only etc.), which appears to mean we can't use it at all.

It would be helpful if the library were relicensed as LGPL or GPL2+ or something like that, toward GPL3 compatibility.

**Comment by kdsoss** [comment]
License changed……

**Comment by kdsoss** [comment]
Complete

**Comment by kdsoss** [comment]
Issue solved

**Comment by fche** [comment]
Wow, thanks!

**Comment by pevik** [comment]
For a record, implemented in 6adc50f68202294e7c603b7fc60edfd018c33542.

@mimizohar FYI the subject about (https://github.com/linux-integrity/ima-evm-utils) shows `LGPL-2.1, GPL-2.0 licenses found`, referring to https://github.com/linux-integrity/ima-evm-utils/blob/next-testing/COPYING and https://github.com/linux-integrity/ima-evm-utils/blob/next-testing/COPYING.LESSER.

**Comment by mimizohar** [comment]
On Mon, 2024-07-08 at 04:11 -0700, Petr Vorel wrote:
Thanks Petr for catching it!   I've removed the commit in next-testing.
Mimi

**Comment by pevik** [comment]
@mimizohar @kdsoss 6adc50f68202294e7c603b7fc60edfd018c33542 also removed openssl exception, which is IMHO wrong. AFAIK @mimizohar you should create project specific exception, see https://spdx.org/licenses/exceptions-index.html and https://github.com/spdx/license-list-XML/pull/1969.

**Comment by kdsoss** [comment]
@pevik Hi, how do you think we should address this exception now? Thanks
